import {
  Shield,
  Database,
  Bell,
  AlertTriangle,
  Users,
  Fingerprint,
  Eye,
  Key,
  Clock,
  Activity,
  ChevronRight,
  Menu,
  Sun,
  Moon,
  LogOut,
  Sliders,
  Settings,
  HelpCircle,
  FileText,
  Download,
  Search,
  Filter,
  CheckCircle2,
  XCircle,
  Play,
  Pause,
  RotateCcw,
  AlertCircle,
  UserCheck,
  TrendingUp,
  FileSpreadsheet,
  Network
} from "lucide-react";

export const IconRegistry = {
  Security: Shield,
  Database: Database,
  Alerts: Bell,
  Critical: AlertTriangle,
  Employees: Users,
  Identity: Fingerprint,
  Monitoring: Eye,
  PrivilegedAccess: Key,
  Timeline: Clock,
  Behaviour: Activity,
  ChevronRight: ChevronRight,
  Menu: Menu,
  Sun: Sun,
  Moon: Moon,
  Logout: LogOut,
  Sliders: Sliders,
  Settings: Settings,
  Help: HelpCircle,
  Report: FileText,
  Download: Download,
  Search: Search,
  Filter: Filter,
  Success: CheckCircle2,
  Error: XCircle,
  Play: Play,
  Pause: Pause,
  Reset: RotateCcw,
  Info: AlertCircle,
  Approvals: UserCheck,
  Metrics: TrendingUp,
  Audit: FileSpreadsheet,
  Network: Network
};

export type IconType = keyof typeof IconRegistry;
